# Generated by Django 5.1.6 on 2025-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encuesta', models.CharField(max_length=100)),
                ('contenido', models.JSONField(blank=True, null=True)),
                ('respuestas', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
