# Generated by Django 5.1.6 on 2025-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapist',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='subscription_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
