# Generated by Django 5.1.6 on 2025-03-25 17:53

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], max_length=14),
        ),
    ]
