# Generated by Django 5.1.6 on 2025-03-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='physiotherapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='users.physiotherapist'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='users.patient'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to='treatments.exercise'),
        ),
        migrations.AddField(
            model_name='series',
            name='exercise_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='treatments.exercisesession'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='treatments.series'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to='treatments.session'),
        ),
        migrations.AddField(
            model_name='sessiontest',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='treatments.session'),
        ),
        migrations.AddField(
            model_name='sessiontestresponse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_responses', to='users.patient'),
        ),
        migrations.AddField(
            model_name='sessiontestresponse',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='treatments.sessiontest'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='physiotherapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='users.physiotherapist'),
        ),
        migrations.AddField(
            model_name='session',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treatments.treatment'),
        ),
    ]
