# Generated by Django 5.1.6 on 2025-03-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_initial'),
        ('treatments', '0003_alter_session_day_of_week'),
    ]

    operations = [
    ]
