# Generated by Django 5.1.6 on 2025-03-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.admin'),
        ),
    ]
