# Generated by Django 5.1.6 on 2025-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='tag',
            field=models.CharField(choices=[('terms', 'Terms of Use'), ('cookies', 'Cookie Policy'), ('privacy', 'Privacy Policy'), ('license', 'License')], default='terms', max_length=20),
        ),
    ]
