# Generated by Django 5.1.6 on 2025-03-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamientos', '0001_initial'),
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(choices=[('UPPER_BODY', 'Parte Superior del Cuerpo'), ('LOWER_BODY', 'Parte Inferior del Cuerpo'), ('CORE', 'Zona Media/Core'), ('FULL_BODY', 'Cuerpo Completo'), ('SHOULDER', 'Hombros'), ('ARM', 'Brazos (Bíceps, Tríceps)'), ('CHEST', 'Pecho'), ('BACK', 'Espalda'), ('QUADRICEPS', 'Cuádriceps'), ('HAMSTRINGS', 'Isquiotibiales'), ('GLUTES', 'Glúteos'), ('CALVES', 'Pantorrillas'), ('NECK', 'Cuello'), ('LOWER_BACK', 'Zona Lumbar'), ('HIP', 'Caderas'), ('BALANCE', 'Ejercicios de Equilibrio'), ('MOBILITY', 'Movilidad'), ('STRETCHING', 'Estiramientos'), ('PROPRIOCEPTION', 'Propiocepción')], max_length=255)),
                ('material_required', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_type', models.CharField(choices=[('REPS_WEIGHT', 'Repeticiones y Carga'), ('REPS_TIME', 'Repeticiones y Tiempo')], max_length=20)),
                ('series', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to='gestion_tratamientos.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('repetitions_done', models.IntegerField(blank=True, null=True)),
                ('weight_done', models.FloatField(blank=True, null=True)),
                ('time_done', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='gestion_usuarios.patient')),
                ('exercise_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='gestion_tratamientos.exercisesession')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gestion_tratamientos.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to='gestion_tratamientos.session'),
        ),
    ]
