# Generated by Django 5.1.6 on 2025-03-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamientos', '0002_exercise_exercisesession_exerciselog_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
