# Generated by Django 5.1.6 on 2025-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='hora')),
                ('patient_id', models.IntegerField(verbose_name='Id_Paciente')),
                ('physiotherapist_id', models.IntegerField(verbose_name='Id_fisio')),
                ('reason', models.CharField(max_length=200, verbose_name='motivo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Citas',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
