# Generated by Django 5.1.6 on 2025-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Sin título', max_length=100, verbose_name='title'),
        ),
    ]
