# Generated by Django 5.1.6 on 2025-03-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_appointment_description_appointment_title'),
        ('gestion_usuarios', '0005_remove_physiotherapist_account_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='title',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='gestion_usuarios.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='physiotherapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_appointments', to='gestion_usuarios.physiotherapist', verbose_name='Physiotherapist'),
        ),
    ]
