# Generated by Django 5.1.6 on 2025-03-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_appointment_description_appointment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='alternatives',
            field=models.JSONField(blank=True, null=True, verbose_name='alternatives'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('booked', 'Booked'), ('pending', 'Pending')], default='booked', max_length=50, verbose_name='status'),
        ),
    ]
