# Generated by Django 5.1.6 on 2025-03-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0003_appointment_alternatives_alter_appointment_status'),
        ('gestion_citas', '0003_remove_appointment_description_and_more'),
    ]

    operations = [
    ]
