# Generated by Django 5.1.6 on 2025-03-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_key', models.CharField(max_length=500, unique=True)),
                ('patients', models.ManyToManyField(blank=True, related_name='videos', to='gestion_usuarios.patient')),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gestion_usuarios.physiotherapist')),
            ],
        ),
    ]
