# Generated by Django 5.1.6 on 2025-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0004_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotherapist',
            name='account_status',
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='collegiate_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
