# Generated by Django 5.1.6 on 2025-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_remove_physiotherapist_account_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='specializations',
            field=models.ManyToManyField(related_name='physiotherapists', to='gestion_usuarios.specialization'),
        ),
    ]
