# Generated by Django 5.1.6 on 2025-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_specialization_physiotherapist_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
