# Generated by Django 5.1.6 on 2025-03-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Card', max_length=50)),
                ('status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Canceled', 'Canceled'), ('redeemed', 'redeemed')], default='Not Paid', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_setup_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointment.appointment')),
            ],
        ),
    ]
